# Generated by Django 3.2.3 on 2021-06-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.CharField(default='', max_length=30)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(default='', max_length=250)),
                ('is_login', models.IntegerField(default=0)),
            ],
        ),
    ]
