# Generated by Django 3.2.3 on 2021-06-07 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20210605_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_info',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='money_info',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='money_info',
            name='currency',
            field=models.CharField(default='fa fa-inr', max_length=20),
        ),
    ]
