# Generated by Django 3.2.3 on 2021-06-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_schedule_tr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='money_info',
            name='currency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule_tr',
            name='added_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule_tr',
            name='repeat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction_info',
            name='added_on',
            field=models.DateField(),
        ),
    ]
