# Generated by Django 3.2.3 on 2021-06-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_auto_20210608_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='iconname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='money_info',
            name='budget',
            field=models.IntegerField(),
        ),
    ]
