# Generated by Django 3.2.3 on 2021-06-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_auto_20210612_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_info',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
